### ISSUE TITLE
question about usage

### ISSUE THREAD

**Issue by fire717** [lucidrains/ema-pytorch#11]
Hi!
I want to use ema like this:  save ema model weights, and load the saved weights as normal weights, is this the right usage?

```
ema_model = EMA(model)

#train
output = model(data)

#val 
output = ema_model.ema_model(data)
ema_model.update()

#save 
torch.save(ema_model.ema_model.state_dict(), save_name)

#load 
model.load_state_dict(torch.load(save_name), strict=True)
```

**Comment by lucidrains** [comment]
yup! would it help if I added a method for setting the online model weights and buffer with the EMAs?

**Comment by lucidrains** [comment]
nit: you should call `ema_model.update()` before the validation

**Comment by fire717** [comment]
Thx! I think it's good enough now!

**Comment by lucidrains** [comment]
@fire717 no problem

added it [anyways](https://github.com/lucidrains/ema-pytorch/blob/main/ema_pytorch/ema_pytorch.py#L128) in case you have a special need for it
