### ISSUE TITLE
Post-hoc ema?

### ISSUE THREAD

**Issue by elyxlz** [lucidrains/ema-pytorch#14]
From Karras' recent paper:
https://arxiv.org/abs/2312.02696

Allows you to set the EMA parameters after training is completed.

**Comment by lucidrains** [comment]
nice, love his papers. I'll give it a read later

what's the tldr for the new EMA technique?

**Comment by elyxlz** [comment]
He makes two contributions actually,
The simpler one is just modifying the decay such that Beta is a function of the training time step, this is such to make the averaging profile scale automatically with training time.
![image](https://github.com/lucidrains/ema-pytorch/assets/58893694/e34f99cd-49cf-4b56-a5b0-5d54b9124ee0)


Then there is the post-hoc one, where AFAICT you keep two running EMAs with different profiles at the same time and periodically snapshot the parameters (e.g. every 5k steps). Then at the end of training you pick what profile you want and you run a least squares fit between your two runs to find with what weights you need to interpolate your two runs to achieve the desired profile.
![image](https://github.com/lucidrains/ema-pytorch/assets/58893694/5ba671d9-67db-4a08-b413-9aad87060285)

I still haven't understood it perfectly, however

**Comment by elyxlz** [comment]
It seems like someone recently managed to make an implementation:
https://github.com/cloneofsimo/karras-power-ema-tutorial

**Comment by lucidrains** [comment]
@elyxlz i see

yea, the first can def be added quite easily to the repo

the second one will require more thought

**Comment by lucidrains** [comment]
but first i should read the paper to understand if significant improvements are to be made by being able to do post-hoc EMA in the first place

**Comment by lucidrains** [comment]
oh man, this paper is real good. so many juicy findings, and successful use of cosine sim attention!

I think I'll build out this post hoc EMA

notice that Karras states that he plans to release both implementation and trained models

**Comment by lucidrains** [comment]
<img width="504" alt="Screen Shot 2024-01-08 at 7 39 09 PM" src="https://github.com/lucidrains/ema-pytorch/assets/108653/feae63fc-58bd-4b49-af0c-5e67adfe5fcc">

@elyxlz oh, this makes it easy 🤣

**Comment by lucidrains** [comment]
@elyxlz hey, going to knock it out this morning

also have the magnitude preserving unet finished over [here](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/karras_unet.py)

**Comment by lucidrains** [comment]
@elyxlz Tero Karras really reasons about neural network architectures on another level

**Comment by lucidrains** [comment]
@elyxlz how does the following API look? https://github.com/lucidrains/ema-pytorch/pull/17/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R54

**Comment by lucidrains** [comment]
ok it is done

**Comment by elyxlz** [comment]
it looks awesome! excited to try it out
