### ISSUE TITLE
Post-hoc EMA with non-deepcopyable model

### ISSUE THREAD

**Issue by kalekundert** [lucidrains/ema-pytorch#33]
I'm trying to figure out how to use the `PostHocEMA` module with a model that can't be deep copied.  I see that `KarrasEMA` has a `ema_model` argument meant to accommodate this use case, but there doesn't seem to be a way to specify it via `PostHocEMA`.

If I haven't just overlooked something, would you be interested in a PR to address this?  I think the simplest fix would look something like this:

- Add an `ema_models` argument to `PostHocEMA`.  This would have to be a list of models, with the same length as `gammas`.
- Add `ema_model` and `tmp_ema_model` arguments to `PostHocEMA.synthesize_ema_model()`.

Alternatively, the `model` argument could be changed to accept either a `nn.Module` or a zero-argument callable that returns a `nn.Module`.  This would probably be a slightly bigger change under the hood, but I think the resulting API would be a bit nicer.

**Comment by lucidrains** [comment]
@kalekundert hey Kale, do you want to see if `0.7.4` works for you for the `PostHocEMA` ?

**Comment by kalekundert** [comment]
I haven't tried `PostHocEMA` yet, but I did notice that `0.7.4` breaks the old `ema_model` argument to `EMA`.  I think the problem is here:
https://github.com/lucidrains/ema-pytorch/blob/7f6cd7511e4b4726b09087c5a37584f012dc2ad7/ema_pytorch/ema_pytorch.py#L104-L105

Because torch modules are also callable, this code triggers even if the user passes an instantiated torch module.  I think the code instead needs to be `if not isinstance(ema_model, nn.Module):`.

**Comment by lucidrains** [comment]
@kalekundert oops, yes you are right! thank you

**Comment by kalekundert** [comment]
I ran into one other issue while testing `PostHocEMA`, but I made a PR to fix it: #34

**Comment by lucidrains** [comment]
@kalekundert thanks for the pull request! 🙏

**Comment by kalekundert** [comment]
Thanks for implementing this feature so quickly!
