### ISSUE TITLE
Memory leak in PostHocEMA during checkpointing

### ISSUE THREAD

**Issue by xandergos** [lucidrains/ema-pytorch#35]
I have been facing a memory leak issue in one my projects that uses PostHocEMA. After testing, I was able to narrow down the issue to the checkpointing code:

```python
def checkpoint(self):
    step = self.step.item()
    for ind, ema_model in enumerate(self.ema_models):
        filename = f'{ind}.{step}.pt'
        path = self.checkpoint_folder / filename
        
        pkg = deepcopy(ema_model).to(self.checkpoint_dtype).state_dict()
        torch.save(pkg, str(path))
```

The issue appears to be with the deepcopy. Replacing `deepcopy(ema_model).to(self.checkpoint_dtype).state_dict()` with `ema_model.state_dict()` solves the issue, although it makes "checkpoint_dtype" irrelevant. I suspect the cause of the issue is that `nn.Module` has internal variables that are copied and prevent it from being garbage collected.

This is a fix that appears to work, which only copies the state_dict values and moves them to cpu to prevent GPU memory from accumulating. 
```python
pkg = ema_model.state_dict()
pkg = {k: v.to(device='cpu', dtype=self.checkpoint_dtype, copy=True) for k, v in pkg.items()}
torch.save(pkg, str(path))
```

**Comment by lucidrains** [comment]
@xandergos thank you Alexander, i made the change in 0.7.7!

**Comment by xandergos** [comment]
Thanks for the quick work!

**Comment by lucidrains** [comment]
@xandergos you basically gave me the code lol
