### ISSUE TITLE
Implementation error

### ISSUE THREAD

**Issue by sbl1996** [lucidrains/ema-pytorch#8]
https://github.com/lucidrains/ema-pytorch/blob/d65f4e3031067055a944282583afc5702d8592ad/ema_pytorch/ema_pytorch.py#L112
I think it should be `for name, buffer in model.named_buffers():`.

A related hint for users: do not forget to call `ema.eval()` in your evaluation loop.

**Comment by lucidrains** [comment]
@sbl1996 ah yes, thank you :disappointed:
