### ISSUE TITLE
Using EMA in a DDP setup

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [lucidrains/ema-pytorch#9]
Hello,

I'm wondering if I should only call the EMA function on rank 0 or on all gpus 
for a DDP setup. 

Thanks.

**Comment by lucidrains** [comment]
@JamesMcCullochDickens just do rank 0, unless you plan on sampling a lot of images during eval

**Comment by JohnHerry** [comment]
> @JamesMcCullochDickens just do rank 0, unless you plan on sampling a lot of images during eval and need it distributed

but there is a `update_model_with_ema_every` option to update online model with ema parameters.  If just do rank 0, model copys on other devices should not know the updated parameters , then is It make any sense to improve the follwing traning?

**Comment by 980202006** [comment]
Same issue! Is there any new progress? It is true that the model will copy the EMA parameters to the online model after a certain step.
@JohnHerry @lucidrains
